# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

steps:
  - id: Install dependencies
    name: python:3.11
    dir: retrieval_service
    script: pip install -r requirements.txt -r requirements-test.txt --user

  - id: Update config
    name: python:3.11
    dir: retrieval_service
    secretEnv:
      - DB_USER
      - DB_PASS
    script: |
        #!/usr/bin/env bash
        # Create config
        cp example-config-alloydb.yml config.yml
        sed -i "s/my_database/${_DATABASE_NAME}/g" config.yml
        sed -i "s/my-user/$$DB_USER/g" config.yml
        sed -i "s/my-password/$$DB_PASS/g" config.yml
        sed -i "s/my-project/$PROJECT_ID/g" config.yml
        sed -i "s/my-region/${_ALLOYDB_REGION}/g" config.yml
        sed -i "s/my-cluster/${_ALLOYDB_CLUSTER}/g" config.yml
        sed -i "s/my-instance/${_ALLOYDB_INSTANCE}/g" config.yml

  - id: Run Alloy DB integration tests
    name: python:3.11
    dir: retrieval_service
    env: # Set env var expected by tests
      - "DB_NAME=${_DATABASE_NAME}"
      - "DB_PROJECT=$PROJECT_ID"
      - "DB_REGION=${_ALLOYDB_REGION}"
      - "DB_CLUSTER=${_ALLOYDB_CLUSTER}"
      - "DB_INSTANCE=${_ALLOYDB_INSTANCE}"
    secretEnv:
      - DB_USER
      - DB_PASS
    script: |
        #!/usr/bin/env bash
        python -m pytest datastore/providers/alloydb_test.py

substitutions:
  _DATABASE_NAME: test_${SHORT_SHA}
  _DATABASE_USER: postgres
  _ALLOYDB_REGION: "us-central1"
  _ALLOYDB_CLUSTER: "my-alloydb-cluster"
  _ALLOYDB_INSTANCE: "my-alloydb-instance"

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/alloy_db_user/versions/latest
      env: DB_USER
    - versionName: projects/$PROJECT_ID/secrets/alloy_db_pass/versions/latest
      env: DB_PASS

options:
  automapSubstitutions: true
  substitutionOption: 'ALLOW_LOOSE'
  dynamic_substitutions: true
